import type { BossDef } from '../core/types';

// Archetypes are the point: tanky bosses reward Power, hard hitters reward Guard,
// so the best stamina split keeps moving and never gets "solved".
export const BOSSES: BossDef[] = [
  {
    name: 'A Rooster With Opinions',
    archetype: 'Balanced',
    hp: 94,
    atk: 3,
    gold: 25,
    memories: 1,
    taunt: 'It has thoughts about your posture.',
    defeat: 'The rooster concedes the argument. Market day is open to you.',
    victory: 'The rooster wins. It will be insufferable about this.',
  },
  {
    name: 'The Goose (Ancient Enemy)',
    archetype: 'Hard hitter',
    hp: 420,
    atk: 6,
    gold: 50,
    memories: 1,
    taunt: 'Honk. (This is a threat.)',
    defeat: 'The goose retreats. The barnyard is yours to roam.',
    victory: 'Honk. (This is a victory lap.)',
  },
  {
    name: 'Steward Gerald',
    archetype: 'Tanky',
    hp: 720,
    atk: 4,
    gold: 120,
    memories: 2,
    taunt: 'Gerald has a clipboard. Gerald has never been hit.',
    defeat: 'Gerald is hit. Gerald writes it down. You feel you could start over, wiser.',
    victory: 'Gerald fines you for wasting his afternoon.',
  },
  {
    name: "Gerald's Larger Brother",
    archetype: 'Hard hitter',
    hp: 700,
    atk: 14,
    gold: 300,
    memories: 4,
    taunt: 'He does not have a clipboard. He does not need one.',
    defeat: 'He goes to tell Gerald. The woods are open.',
    victory: 'You wake up in a hay bale. Different hay bale. Somehow worse.',
  },
  {
    name: 'A Bear (Unrelated)',
    archetype: 'Balanced',
    hp: 2100,
    atk: 18,
    gold: 700,
    memories: 8,
    taunt: 'It wandered in. Nobody knows whose bear it is.',
    defeat: 'The bear leaves. It was never about you.',
    victory: 'The bear sits on you, briefly, and leaves.',
  },
  {
    name: 'The Tax Collector',
    archetype: 'Tanky',
    hp: 5800,
    atk: 20,
    gold: 1600,
    memories: 16,
    taunt: 'He is owed. He is always owed.',
    defeat: 'He drops his ledger. You find the Old Mill on page four.',
    victory: 'He collects. Your dignity is assessed at 0 coin.',
  },
  {
    name: "The Miller's Cat",
    archetype: 'Hard hitter',
    hp: 5300,
    atk: 100,
    gold: 4000,
    memories: 32,
    taunt: 'It knocks your hope off the table. Maintains eye contact.',
    defeat: 'The cat decides you are acceptable. For now.',
    victory: 'The cat was never in danger. The cat wants you to know that.',
  },
  {
    name: 'Sir Reginald the Moderately Brave',
    archetype: 'Balanced',
    hp: 17000,
    atk: 140,
    gold: 9000,
    memories: 64,
    taunt: 'He has a horse. Well. He has most of a horse.',
    defeat: 'Sir Reginald bravely runs away, moderately.',
    victory: 'Sir Reginald is moderately pleased with himself.',
  },
  {
    name: "The Bailiff's Mum",
    archetype: 'Hard hitter',
    hp: 20000,
    atk: 410,
    gold: 20000,
    memories: 128,
    taunt: 'She is disappointed in you specifically.',
    defeat: "She says she's not angry. She's furious. She lets you pass.",
    victory: 'She tells your mum. Your mum agrees with her.',
  },
  {
    name: 'The Bailiff',
    archetype: 'Tanky',
    hp: 92000,
    atk: 300,
    gold: 50000,
    memories: 256,
    taunt: 'The law, the land, and a very large stick.',
    defeat: 'The Bailiff falls. Somewhere, a Lord notices a serf. (End of prototype. Keep going if you like.)',
    victory: 'The Bailiff fills out paperwork about you. It is three pages long.',
  },
];
