import type { ZoneDef } from '../core/types';

// Harder zones drop better loot, but you die more and dying costs recovery time.
export const ZONES: ZoneDef[] = [
  {
    name: 'The Barnyard',
    unlockBoss: 2,
    enemies: ['Angry Hen', 'Feral Piglet', 'A Rake (Stepped On)', 'Hen With A Grudge'],
    hp: 25,
    atk: 6,
    gold: 2,
    dropChance: 0.12,
    loot: [
      { item: 'bucketHat', weight: 3 },
      { item: 'usedBucket', weight: 3 },
      { item: 'pitchfork', weight: 3 },
      { item: 'leftBoot', weight: 3 },
      { item: 'rightBoot', weight: 2 },
      { item: 'luckyFeather', weight: 2 },
      { item: 'hayHat', weight: 2 },
    ],
    flavor: 'Mud, feathers, and a rake that has been waiting for you.',
  },
  {
    name: 'The Woods',
    unlockBoss: 4,
    enemies: ['Suspicious Badger', 'Lost Tax Collector', 'Wolf (Small)', 'A Very Old Squirrel'],
    hp: 200,
    atk: 25,
    gold: 12,
    dropChance: 0.1,
    loot: [
      { item: 'badgerHat', weight: 3 },
      { item: 'barkVest', weight: 3 },
      { item: 'sharpStick', weight: 3 },
      { item: 'squelchyBoots', weight: 3 },
      { item: 'mushroom', weight: 2 },
      { item: 'turnip', weight: 2 },
    ],
    flavor: 'Technically the Lord owns these woods. The badgers disagree.',
  },
  {
    name: 'The Old Mill',
    unlockBoss: 6,
    enemies: ['Highwayman', "Miller's Apprentice", 'Flour Ghost', 'Rat (Ambitious)'],
    hp: 2000,
    atk: 120,
    gold: 90,
    dropChance: 0.08,
    loot: [
      { item: 'potHelm', weight: 3 },
      { item: 'flourTunic', weight: 3 },
      { item: 'rustySword', weight: 3 },
      { item: 'highwayBoots', weight: 3 },
      { item: 'millstone', weight: 2 },
      { item: 'goldenTurnip', weight: 0.5 },
    ],
    flavor: 'The wheel still turns. Nobody is turning it.',
  },
];
